# fly.toml app configuration file generated for feed-me-app on 2026-02-14T17:38:28-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'feed-me-app'
primary_region = 'sjc'

[build]

[env]
  PHX_HOST = "2troys.com"
  ECTO_IPV6 = "true"
  DNS_CLUSTER_QUERY = "feed-me-app.internal"

[deploy]
  release_command = "/app/bin/migrate"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[mounts]]
  source = 'uploads_data'
  destination = '/app/uploads'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
